### ISSUE TITLE
Add support for Rocksmith 2014 base game songs

### ISSUE THREAD

**Issue by LegitGreenBoi** [yassineim/cdlc_player#4]
It would be nice if this app were able to import the base game songs from RS2014.

The base game songs seem to be all stored in the 'songs.psarc' file in the root of the game files. Currently this app doesn't seem to be able to read the songs present in this file.

**Comment by AkiraKusanagi** [comment]
This would probably be tricky, as the base game's "songs.psarc" file is probably a bunch of songs compiled. So it's not a single song's file, but rather a bunch of songs put together. CDLC Player is made to play DLC, which is one song file each. So it would probably be tricky going from like, reading single songs, to reading a compilation of a bunch of songs put in one file. Still awaiting judgement from the dev(s) though.

**Comment by AkiraKusanagi** [comment]
This would be nice to add though.

**Comment by AkiraKusanagi** [comment]
Oh yeah, theoretically, if you were to use the Custom Songs Toolkit, (and maybe some python programs for RS songs) then somehow split up the songs one by one into separate psarc files, they should be read. However this would probably take a lot of time and effort, which would suck instead of the app reading having to just read one file and putting in a bunch of songs from there.

**Comment by yassineim** [comment]
@AkiraKusanagi @LegitGreenBoi can your try please? Do note that it takes a very long time to add all songs.
https://github.com/yassineim/cdlc_player/releases/download/lyrics-v8.1/app-release.apk

**Comment by yassineim** [comment]
This one should be faster:
https://github.com/yassineim/cdlc_player/releases/download/lyrics-v9/app-release.apk

**Comment by LegitGreenBoi** [comment]
> @AkiraKusanagi @LegitGreenBoi can your try please? Do note that it takes a very long time to add all songs. https://github.com/yassineim/cdlc_player/releases/download/lyrics-v8.1/app-release.apk

Works great! Thanks for getting these out so quickly :)
